# -*- coding: utf-8 -*-
"""PalmerPenguinsM2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eul0NaSnStbGJZXs9X0yquWFdiw05iGW
"""

# PalmerPenguins.py
# Raynette Brown
# 09.12.2026
# Calculates and displays Palmer Penguin statistics

# constants representing the species and count
SP_CHINSTRAP = "Chinstrap"
SP_GENTOO = "Gentoo"
SP_ADELIE = "Adelie"

TOTAL_SPECIES = 3

# add constants for the number of penguins
NUM_CHINSTRAP = 68
NUM_GENTOO = 123
NUM_ADELIE = 151

#calculate the total number of penguins
num_species = 3
total_penguins = NUM_CHINSTRAP + NUM_GENTOO + NUM_ADELIE

#calculate the average number of penguins per species
average_penguins = total_penguins/TOTAL_SPECIES

#calculate the percentage of each species
chinstrap_percent = NUM_CHINSTRAP / total_penguins * 100
gentoo_percent = NUM_GENTOO / total_penguins * 100
adelie_percent = NUM_ADELIE / total_penguins * 100

#math Module
average_rounded = math.ceil(average_penguins)

# output the species names with introductory text

print("Introducing the Palmer Penguins")
print("\t" + SP_CHINSTRAP + "!")
print("\t" + SP_GENTOO + "!")
print("and last but not least...")
print("\t" + SP_ADELIE + "!")
print()


print("There are a total of " + str(TOTAL_SPECIES) + " penguin species in this dataset.")
print("There are a total of " + str(total_penguins) + " penguins in this dataset.")
print("The average number of penguins per species is " + str(average_penguins) + ".")
print("The average number of penguins per species is " + str(average_rounded) + ".")

print(SP_CHINSTRAP + ": " + str(NUM_CHINSTRAP) + " (" + str(chinstrap_percent) + "%)")
print(SP_GENTOO + ": " + str(NUM_GENTOO) + " (" + str(gentoo_percent) + "%)")
print(SP_ADELIE + ": " + str(NUM_ADELIE) + " (" + str(adelie_percent) + "%)")